name: INFINITE COUNCIL
favicon: null
layout_spectrum: 0.12354127829894423
typography_spectrum: 0.43591161351650953
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#110101'
    - '#a49167'
    - '#47431e'
    - '#e44d2d'
    - '#dae132'
  brandStrength: 0.271817690692842
  lightness: 0.7606490824837238
  saturation: 0.3306061860639602
  rhythmicContrast: 0.8717964973766357
purpose: []
